# Site
repository: rishabhverma17/github-io-resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Rishabh Verma
title: Engineering @ Microsoft
email: rishabhverma17@gmail.com
website: resume.rishabhverma.in

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: rishabhverma24
github_username:  rishabhverma17
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: rishabhverma1
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
additional_links:
- title: View or Download My Resume
  icon: fas fa-file-download
  url: https://rishabhverma17.github.io/DevOpsing_Resume/Resume_RishabhVerma_SDE.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
gtm: "GTM-MZCR6QT"
gtag: "UA-206187355-1"
google_analytics: "UA-206187355-1"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Rishabh and I'm a Software Development Engineer 2 @ Microsoft. I have experience in developing low latency, highly scalable, fault-tolerant, distributed backend services and evolving the architecture for performance and scalability.Experience of Object-Oriented Programming, Object-Oriented Design, Messaging, Event Streaming,Data Structures and Algorithms, Prevalent Design Patterns, Caching,NoSQL, RDBMS.

  I am most skilled in: <mark>Distributed Systems</mark> and <mark>Eating Pizza</mark>

content:
  - title: Technical Skills # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        description: | # this will include new lines to allow paragraphs
          <mark>Tech Stack:</mark> C#, Azure Service Fabric, Azure Service Bus, Azure, Cosmos, Redis, Java 8, SpringBoot, MySQL, Cassandra, MongoDB, Aerospike, RESTful API’s, Kafka, Microservices, Data Structures, Algorithms, ELK
          
          <mark>Tools:</mark> App Insights, Geneva Logging, Kusto, KQL, GIT, Jenkins, Maven, Gradle, Kubernetes, Docker, Pinpoint, Icinga, Grafana, Kibana

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Microsoft
        link: microsoft.com
        link_text: microsoft.com
        sub_title: Software Development Engineer II
        caption: May 2022 - Present
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          <mark>Pre-Prod Infra:</mark> Led the creation of a new integration infrastructure for our services, facilitating the establishment of a pre-production environment for cross-functional teams.

          <mark>Migrated from EUA to EUAM:</mark> Successfully migrated multiple services from EUA to EUAM, ensuring seamless authorization and role management with zero downtime.

          <mark>Surface Program:</mark> Contributed to the post-enrollment phase of the Surface Partner Onboarding to Partner Center, enhancing the overall partner experience.
          
          <mark>AAD Graph to MS Graph Migration:</mark> Spearheaded the migration of our services from AAD Graph to MS Graph, improving service efficiency and reliability.

  
      - layout: left
        title: Snapdeal
        link: snapdeal.com
        link_text: snapdeal.com
        sub_title: Software Development Engineer II
        caption: March 2021 - May 2022
        quote: >
          My team and I are responsible for key services such as Checkout, Cart Service, Post Order Management, Order Payment Management Service, Order Management Service, Promotions, Payments, and the API aggregator service.
        description: | # this will include new lines to allow paragraphs
            <mark>Snapdeal Pro Subscription:</mark> This system allows users to purchase various plans to access greater discounts and superior offers compared to non-subscription users.
            
            <mark>Reward & Referral System:</mark>  successfully designed and deployed a new Referral and Reward service from the ground up. My responsibilities encompassed high-level and low-level system design, service implementation, and production deployment. Initial statistics indicate that an average of 63,000+ new and returning users sign up daily for this program, positively impacting sales and customer retention
            
            <mark>Checkout Service:</mark> Improved the checkout service API’s by pre-processing time taking tasks asynchronously and caching external network calls resulting in reduced overall response time by 30% .
            
            <mark>OPMS:</mark> Introduced a automated Dynamic Rate Limiter and moved credit call from Sync to Async flow which can handles the rate limiting dynamically at runtime. Reducing load on service and making it much easier to re-try in case of errors.
            

      - layout: left
        title: Yatra Online Pvt Ltd
        link: yatra.com
        link_text: yatra.com
        sub_title: Software Development Engineer
        caption: January 2020 - February 2021
        quote: >
          Worked in their Hotels Engineering core team.
        description: | # this will include new lines to allow paragraphs
            <mark>Build Your Own Package:</mark> Holidays Platform: Developed a novel platform at Yatra that allows users to create their own holiday packages. Users can choose their preferred destination(s) and travel date(s), and we offer them a curated package that balances cost-effectiveness and quality. This package includes Hotel and Travel arrangements (either Flight or Intra/Inter state CAB). The platform is designed to be user-friendly, allowing customers to modify any component of the base package to suit their individual needs.
            
            <mark>Central Logging Pipeline:</mark> Engineered a central logging service to track metrics from external microservices. This service is designed to be universal and easily integrated with all other microservices.
            
            <mark>Auto Suggest:</mark> Created a new de-duplication pipeline for better results.


      - layout: left
        title: Delhi Integrated Multi Modal Transit System
        link: dimts.in
        link_text: dimts.in
        sub_title: Software Development Engineer
        caption: January 2019 - January 2020
        description: | # this will include new lines to allow paragraphs
            <mark>Designed DMRC and DIMTS Reconciliation System:</mark> Implemented a system that significantly improved the reconciliation process, reducing the time required by 70% and eliminating the need for manual effort.
            
            <mark>Developed Automated Recovery Service:</mark> Created a tool designed to automatically recover trips and shifts that were corrupted due to operational issues with the ETM machine.
            
            <mark>ETM Challan:</mark> Redesigned ETM Challan module so that ETM machines can be moved more than once a day. Impact: Reduced ETM Movement cost by 30%

      - layout: left
        title: Aperta Limited
        link: aperta.com
        link_text: aperta.com
        sub_title: Software Engineer
        caption: August 2016 - January 2019
        description: | # this will include new lines to allow paragraphs
            <mark>Interface Utility:</mark> Developed an in-house utility for the Interface Utility Bank that interacts with the Core Banking System (CBS) and Cheque Truncation System (CTS). By redesigning the algorithm, the processing time for 70,000 to 100,000 instruments was reduced by 75%, from 16 seconds to less than 4 seconds.
            
            <mark>Clearing House Master:</mark> Developed CHM which reduced overall processing time by 30%: This was achieved by removing bottlenecks, redesigning algorithm and using data structures to aggregate data, process them, create banking software’s business rules and update all Nodal branch systems remotely over network.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Sharda University
        caption: 2012 - 2016
        sub_title: Bachelor Of Technology (B.Tech) in Computer Science
        description: | # this will include new lines to allow paragraphs
          During my time at Sharda I learnt most of my key skills that I have taken through my career such as teamwork and working in tight deadlines. I thouroughly enjoyed my time in university and learnt a lot about a healthy work life balance.
          - <mark>Project:</mark>  [gestureIt](https://gestureit-rishabh.firebaseapp.com/)

  #- title: A Little More About Me
  #  layout: text
  #  content: | # this will include new lines to allow paragraphs
  #    Alongside my interests in networks and software engineering some of my other interests and hobbies are:
  #    - Rock climbing
  #    - Gaming
  #    - Knitting
  #    - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

  #    Look at this cool image  
  #    ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
